scripts:
  - /assets/js/adeptus-ineptus.js
stylesheets:
  - /assets/css/adeptus-ineptus.css
author: The Adeptus Ineptus
title: Adeptus Ineptus

# Where things are
source: _site
destination: public_html
sass:
  style: compressed

# Outputting
timezone: America/New_York

# Outputting
defaults:
  -
    values:
      layout: page
  -
    scope:
      path: assets
    values:
      layout: none

# Theme
theme: baseline
